// Optic definitions for the IV-7 (pure data + math, no three.js rendering, no DOM: Node-testable).
//
// Merges the asset data written by the Blender pipeline (Shared/config/optics.json: magnification, eye point,
// sight axis, eyebox, reticle angular scale, ADS time, rail mount) with the game rules and view settings
// (src/data/attachments.json) and the web asset file names (src/data/optics_web.json, generated by
// Tools/web_assets/build_web_assets.py). 'irons' is the no-optic choice (the rifle's flip-up irons deployed).
//
// Frames: rifle model frame = glTF Y-up of the IV-7 (+X muzzle, +Y up, +Z weapon right, origin at the grip).
// An optic GLB's origin is its socket_rail; it mounts with identity rotation at mount_on_iv7.socket_rail_rifle_m.

import opticsData from '../../../Shared/config/optics.json' with { type: 'json' };
import attachments from '../data/attachments.json' with { type: 'json' };
import opticsWeb from '../data/optics_web.json' with { type: 'json' };
import weaponsData from '../data/weapons.json' with { type: 'json' };

export const IRONS = 'irons';
export const NO_SPARE = null;
const DEG = Math.PI / 180;

/** The rifle's own iron-sight eye point (socket_ads), rifle model frame. */
const IRONS_EYE = weaponsData.iv7_carbine.viewModel.adsEyeLocal.slice();

const byId = new Map(opticsData.optics.map((o) => [o.id, o]));

/** Canonical optic id ('IVR1', ..., 'irons') or null if unknown. Accepts aliases ('collimator'). */
export function resolveOpticId(id) {
  if (id === null || id === undefined) return null;
  const s = String(id);
  const a = attachments.aliases && attachments.aliases[s];
  const k = a || s;
  if (k === IRONS) return IRONS;
  return byId.has(k) ? k : null;
}

/** Spare id: an optic id or null ('none' / null / 'irons' mean no spare optic in the backpack). */
export function resolveSpareId(id) {
  if (id === null || id === undefined || id === 'none' || id === attachments.noSpare.id) return null;
  const r = resolveOpticId(id);
  if (r === IRONS) return null; // the irons are part of the rifle, nothing to carry
  return r || undefined; // undefined = invalid
}

/** Choices for the loadout / armory menus (Czech names), in display order. */
export function opticChoices() {
  return attachments.choices.map((c) => ({ ...c }));
}

export function opticName(id, { short = false } = {}) {
  if (id === null || id === undefined || id === 'none') return short ? attachments.noSpare.short : attachments.noSpare.name;
  const c = attachments.choices.find((x) => x.id === resolveOpticId(id));
  return c ? (short ? c.short : c.name) : String(id);
}

const add3 = (a, b) => [a[0] + b[0], a[1] + b[1], a[2] + b[2]];

const cache = new Map();

/**
 * Full definition of an optic choice.
 * { id, name, short, kind, mode, magnification, adsTime, worldFovMultiplier, eyeRifle, railRifle,
 *   axisFrontRifle, axisRearRifle, eyeboxRadius, lensRadius, eyeRelief, trueFovDeg, reticle, overlay, assets, nodes, sockets }
 */
export function getOpticDef(id) {
  const key = resolveOpticId(id);
  if (!key) throw new Error(`Neznámá optika: ${id}`);
  if (cache.has(key)) return cache.get(key);
  const view = attachments.view[key] || {};
  let def;
  if (key === IRONS) {
    def = {
      id: IRONS,
      name: opticName(IRONS),
      short: opticName(IRONS, { short: true }),
      kind: 'irons',
      mode: 'irons',
      magnification: 1,
      adsTime: weaponsData.iv7_carbine.adsTime,
      worldFovMultiplier: view.worldFovMultiplier ?? weaponsData.iv7_carbine.adsFovMultiplier ?? 1,
      eyeRifle: IRONS_EYE.slice(),
      railRifle: null,
      axisFrontRifle: null,
      axisRearRifle: null,
      reticle: null,
      overlay: null,
      assets: null,
    };
  } else {
    const o = byId.get(key);
    const s = o.sockets_optic_frame_m.gltf_yup;
    const rail = o.mount_on_iv7.socket_rail_rifle_m.gltf_yup.slice();
    const web = (opticsWeb.optics && opticsWeb.optics[key]) || null;
    const r = o.reticle;
    const unitInRad = r.units === 'mrad' ? 0.001 : Math.PI / (180 * 60);
    def = {
      id: key,
      model: o.model,
      name: opticName(key),
      short: opticName(key, { short: true }),
      kind: o.kind,
      mode: view.mode || (o.magnification > 1 ? 'pip' : 'collimated'),
      magnification: o.magnification,
      adsTime: o.ads_time_s,
      worldFovMultiplier: view.worldFovMultiplier ?? 1,
      scopeIn: view.scopeIn ?? 0.9,
      scopeFade: view.scopeFade ?? 0.1,
      railRifle: rail,
      eyeRifle: o.mount_on_iv7.socket_eye_rifle_m.gltf_yup.slice(),
      axisFrontRifle: add3(rail, s.socket_sight_axis_front),
      axisRearRifle: add3(rail, s.socket_sight_axis_rear),
      reticleRifle: add3(rail, s.socket_reticle),
      sockets: s,
      eyeRelief: o.eye_relief_m,
      eyeboxRadius: o.eyebox_radius_m,
      lensRadius: o.lens_radius_m,
      trueFovDeg: o.true_fov_deg,
      zeroM: o.zero_m,
      recommendedRangeM: o.recommended_range_m.slice(),
      reticle: {
        units: r.units,
        unitInRad,
        fieldUnits: r.field_units,
        colourSrgb: r.colour_srgb.slice(),
        minDotPx: r.render_hints.min_dot_diameter_px,
        minStrokePx: r.render_hints.min_stroke_px,
        features: r.features.map((f) => ({ ...f })),
        ...reticleWidths(r.features),
        sdf: web ? { ...web.sdf } : null,
      },
      overlay: o.ads_overlay
        ? {
            vfovDeg: o.ads_overlay.vertical_fov_deg_when_drawn_full_height,
            fieldUnits: o.ads_overlay.field_mrad,
            eyeboxFraction: o.ads_overlay.eyebox_radius_fraction_of_height,
            file: web && web.overlay ? web.overlay.file : null,
            size: web && web.overlay ? web.overlay.size : o.ads_overlay.size_px,
          }
        : null,
      nodes: { ...o.node_names },
      hideRifleNodes: o.mount_on_iv7.hide_rifle_nodes.slice(),
      assets: web ? { glb: web.glb, lod1: web.lod1 } : null,
    };
  }
  Object.freeze(def);
  cache.set(key, def);
  return def;
}

/**
 * Half widths (in reticle units) of the thinnest illuminated / etched stroke and the centre dot radius,
 * from the feature list (dots are handled separately with the min dot size).
 */
export function reticleWidths(features) {
  let lit = Infinity;
  let etched = Infinity;
  let dot = 0;
  for (const f of features) {
    let hw = null;
    if (f.type === 'dot') {
      if (f.layer === 'lit') dot = Math.max(dot, f.diameter / 2);
      else hw = f.diameter / 2;
    } else if (f.type === 'mil_dots') hw = (f.diameter || 0.2) / 2;
    else if (typeof f.stroke === 'number') hw = f.stroke / 2;
    else if (f.type === 'holdover_bar') hw = 0.03; // 0.06 mrad bars (spec section 4)
    if (hw === null) continue;
    if (f.layer === 'lit') lit = Math.min(lit, hw);
    else etched = Math.min(etched, hw);
  }
  return { litHalfWidth: Number.isFinite(lit) ? lit : 0, etchHalfWidth: Number.isFinite(etched) ? etched : 0, dotRadius: dot };
}

/** ADS pose of the view model for this optic: the optic's eye point lands on the camera. */
export function adsPoseFor(def) {
  const e = def.eyeRifle;
  // model root turned +90 deg about Y: model (x, y, z) -> holder (z, y, -x); ADS position = -(eye in holder space)
  return { adsEyeLocal: e.slice(), adsPosition: [-e[2], -e[1], e[0]] };
}

/** weapons.json viewModel block with the ADS pose of the optic (hip pose unchanged). */
export function opticViewModel(baseVm, def) {
  const p = adsPoseFor(def);
  return { ...baseVm, adsEyeLocal: p.adsEyeLocal, adsPosition: p.adsPosition };
}

/** Screen pixels per radian of a camera with vertical FOV `vfovDeg` on a target `heightPx` tall. */
export function pxPerRad(vfovDeg, heightPx) {
  return heightPx / 2 / Math.tan((vfovDeg * DEG) / 2);
}

/**
 * Mouse sensitivity factor while aiming (1 at the hip). With scaling on, the look speed matches the angular
 * speed of the image the player looks at: the tan(fov/2) ratio of the camera that shows it vs the hip view
 * (1x optics with no zoom: 1; irons: the slight ADS zoom; 6x full screen: the zoomed camera; picture-in-picture:
 * 1 / magnification, blended in with the ADS amount like the eyepiece image). The ADS multiplier setting blends
 * in with the ADS amount.
 * @param {object} o { def, ads (0..1), hipVfovDeg, curVfovDeg (main camera now), scaling (bool), multiplier }
 */
export function sensitivityFactor({ def = null, ads = 0, hipVfovDeg, curVfovDeg, scaling = true, multiplier = 1 }) {
  const a = Math.min(Math.max(ads, 0), 1);
  const w = a * a * (3 - 2 * a);
  if (w <= 0) return 1;
  let zoom = 1;
  if (scaling) {
    if (def && def.mode === 'pip') zoom = 1 + (1 / def.magnification - 1) * w;
    else zoom = Math.tan(((curVfovDeg ?? hipVfovDeg) * DEG) / 2) / Math.tan((hipVfovDeg * DEG) / 2);
  }
  return zoom * (1 + (multiplier - 1) * w);
}

/**
 * Dilation (in SDF texels) that keeps a stroke of true half width `halfWidthTexels` at least `minPx` screen
 * pixels wide when one screen pixel covers `texelsPerPx` texels (the shader does the same per fragment).
 */
export function strokeDilation(halfWidthTexels, texelsPerPx, minPx) {
  return Math.max(0, 0.5 * minPx * texelsPerPx - halfWidthTexels);
}

/**
 * Eyebox of a magnified optic: 1 inside, fading to 0 when the eye is off the sight axis by more than the
 * exit-pupil radius or the eye relief is wrong by more than `reliefTolerance` metres.
 * @param lateral  distance of the eye from the sight axis (m)
 * @param reliefError  signed eye-relief error (m)
 */
export function eyeboxFactor(def, lateral, reliefError, reliefTolerance = 0.025) {
  const r = def.eyeboxRadius || 0.005;
  const smooth = (e0, e1, x) => {
    const t = Math.min(Math.max((x - e0) / (e1 - e0), 0), 1);
    return t * t * (3 - 2 * t);
  };
  const lat = 1 - smooth(r, r * 2.2, lateral);
  const rel = 1 - smooth(reliefTolerance, reliefTolerance * 2, Math.abs(reliefError));
  return lat * rel;
}

/** Loadout validation: primary in the choices, spare an optic (or none) different from the primary. */
export function validateOpticLoadout({ optic, spare = null } = {}) {
  const o = resolveOpticId(optic);
  if (!o) return { ok: false, reason: 'unknown_optic' };
  const s = resolveSpareId(spare);
  if (s === undefined) return { ok: false, reason: 'unknown_spare' };
  if (s !== null && s === o) return { ok: false, reason: 'spare_equals_primary' };
  return { ok: true, optic: o, spare: s };
}

/** Bot optic kit by role (attachments.bots.pattern cycled by the bot's index in its team). */
export function botKit(indexInTeam) {
  const B = attachments.bots;
  const role = B.pattern[((indexInTeam % B.pattern.length) + B.pattern.length) % B.pattern.length];
  const r = B.roles[role];
  return { role, roleName: r.name, optic: r.optic, spare: r.spare ?? null };
}

export const ATTACHMENTS = attachments;
export const OPTICS_DATA = opticsData;
export const OPTIC_IDS = opticsData.optics.map((o) => o.id);
