#!/usr/bin/env python3
"""
pack_web_environment.py -- packs the environment source textures (Art/Textures/Environment/...) into the runtime
files of the browser build (Web/public/assets/environment/), deterministically.

Terrain layers (order from Art/Textures/Environment/Terrain/terrain_layers.json):
  terrain/terrain_albedo.jpg   W x (W * layers)  base colour (sRGB), one layer below the other
  terrain/terrain_nh.jpg       W x (W * layers)  R G = tangent normal x / y (OpenGL, 0.5 + 0.5 n), B = blend height
  terrain/terrain_rao.jpg      w x (w * layers)  R = roughness, G = occlusion (half resolution)
  terrain/terrain_layers.json  layer names, tile sizes (m), relief, files
The game slices the strips into WebGL2 texture arrays (src/level/terrainMaterial.js).  Replacing a source set with
a photo-scanned one (same file names, edited <Set>.json) needs no code change: re-run this script.

JPEG 4:4:4 (no chroma subsampling: the channels of the normal / roughness strips are independent data).

The vegetation GLB (models, foliage / grass atlases, bark array) is written by
Art/Source/Blender/environment/vegetation.py (run from here unless --terrain-only).

Usage: python3 Tools/environment/pack_web_environment.py [--size 512] [--terrain-only]
"""
import argparse
import hashlib
import io
import json
import os
import sys

import numpy as np
from PIL import Image, ImageFile, ImageFilter

ImageFile.MAXBLOCK = 1 << 25   # optimised JPEG of large images needs one big buffer (PIL "Suspension not allowed")

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC_TER = os.path.join(ROOT, "Art", "Textures", "Environment", "Terrain")
OUT = os.path.join(ROOT, "Web", "public", "assets", "environment")


def load(path, mode="RGB", size=None):
    im = Image.open(path)
    if im.mode in ("I;16", "I;16B", "I"):
        a = np.asarray(im, np.float64) / 65535.0
        im = Image.fromarray(np.clip(a * 255 + 0.5, 0, 255).astype(np.uint8), "L")
    im = im.convert(mode)
    if size and im.size != (size, size):
        im = im.resize((size, size), Image.LANCZOS)
    return np.asarray(im)


def jpeg(arr, q):
    b = io.BytesIO()
    Image.fromarray(arr).save(b, "JPEG", quality=q, subsampling=0, optimize=True)
    return b.getvalue()


def write(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(data)
    return hashlib.sha256(data).hexdigest()[:16]


def pack_terrain(size):
    man = json.load(open(os.path.join(SRC_TER, "terrain_layers.json")))
    alb, nh, rao, layers = [], [], [], []
    half = size // 2
    for L in man["layers"]:
        nm = L["name"]
        meta = json.load(open(os.path.join(SRC_TER, nm, f"{nm}.json")))
        m = meta["maps"]
        d = os.path.join(SRC_TER, nm)
        a = load(os.path.join(d, m["baseColor"]), "RGB", size)
        # a slight blur of the normal map: less shimmer at grazing angles and a much smaller JPEG
        n = np.asarray(Image.fromarray(load(os.path.join(d, m["normal"]), "RGB", size)).filter(ImageFilter.GaussianBlur(0.6)))
        h = load(os.path.join(d, m["height"]), "L", size)
        orm = load(os.path.join(d, m["orm"]), "RGB", half)
        alb.append(a)
        nh.append(np.dstack([n[..., 0], n[..., 1], h]))
        rao.append(np.dstack([orm[..., 1], orm[..., 0], np.zeros_like(orm[..., 0])]))
        layers.append({"index": L["index"], "name": nm, "tile_m": meta["tile_m"], "relief_m": meta.get("relief_m", 0.02),
                       "mean_base_color_srgb": meta.get("mean_base_color_srgb"), "use": L.get("use", "")})
    files = {}
    files["albedo"] = ("terrain/terrain_albedo.jpg", jpeg(np.concatenate(alb, 0), 84))
    files["nh"] = ("terrain/terrain_nh.jpg", jpeg(np.concatenate(nh, 0), 80))
    files["rao"] = ("terrain/terrain_rao.jpg", jpeg(np.concatenate(rao, 0), 85))
    out = {"_comment": "GENERATED by Tools/environment/pack_web_environment.py from Art/Textures/Environment/Terrain - do not edit.",
           "size": size, "raoSize": half, "count": len(layers), "layers": layers, "files": {}}
    for k, (rel, data) in files.items():
        h = write(os.path.join(OUT, rel), data)
        out["files"][k] = {"path": f"assets/environment/{rel}", "bytes": len(data), "sha": h}
        print(f"  {rel}: {len(data) / 1024:.0f} KiB")
    with open(os.path.join(OUT, "terrain", "terrain_layers.json"), "w") as f:
        json.dump(out, f, indent=1, ensure_ascii=False)
        f.write("\n")
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--size", type=int, default=512)
    ap.add_argument("--terrain-only", action="store_true")
    a = ap.parse_args()
    t = pack_terrain(a.size)
    print(f"terrain: {t['count']} layers @ {t['size']} px")
    if not a.terrain_only:
        # the vegetation GLB (models + atlases) is written by the Blender generator itself
        import subprocess
        subprocess.run([sys.executable, os.path.join(ROOT, "Art", "Source", "Blender", "environment", "vegetation.py")], check=True)


if __name__ == "__main__":
    main()
