// Level geometry shipped as GLB (generated by Tools/level/export_web_level.py): a minimal GLB reader (plain JS,
// no loaders, works in Node and in the browser) and the conversion of its collision content into level solids for
// the BVH collision world (src/physics/collisionWorld.js).
//
//   kh_collision.glb  one mesh per collision set, node extras.iv = { class, surface, nav }:
//                       class main    stops capsules, bullets and sight (walls, floors, roofs, solid props)
//                             move    stops capsules only (window glass, chain-link / picket / pipe-rail fences, hard edge)
//                             movevis stops capsules and sight, bullets pass (hedges, shrubs, soft furniture, crates)
//   kh_terrain.glb    terrain tiles (render + collision, node extras.iv.collision = 'terrain') and the surface raster
//                     (asset.extras.iv.surfaceRaster: u8 surface index per 0.5 m cell, rows north -> south)
// Solids get the id prefix "geo:" so the AI knows the navmesh was baked with them (see src/ai/index.js).

import { BufferGeometry, Float32BufferAttribute } from 'three';

const COMPONENTS = { SCALAR: 1, VEC2: 2, VEC3: 3, VEC4: 4, MAT4: 16 };
const CTYPES = { 5120: Int8Array, 5121: Uint8Array, 5122: Int16Array, 5123: Uint16Array, 5125: Uint32Array, 5126: Float32Array };

/** Parses a GLB container: { json, bin (Uint8Array view of the BIN chunk) }. */
export function parseGlb(buffer) {
  const ab = buffer instanceof ArrayBuffer ? buffer : buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
  const dv = new DataView(ab);
  if (dv.getUint32(0, true) !== 0x46546c67) throw new Error('not a GLB file');
  const total = dv.getUint32(8, true);
  let off = 12;
  let json = null;
  let bin = null;
  while (off < total) {
    const len = dv.getUint32(off, true);
    const type = dv.getUint32(off + 4, true);
    const start = off + 8;
    if (type === 0x4e4f534a) json = JSON.parse(new TextDecoder('utf-8').decode(new Uint8Array(ab, start, len)));
    else if (type === 0x004e4942) bin = new Uint8Array(ab, start, len);
    off = start + len;
  }
  if (!json) throw new Error('GLB without JSON chunk');
  return { json, bin };
}

/** Accessor data as a tightly packed typed array (a copy when the buffer view is strided or unaligned). */
export function readAccessor(glb, index) {
  const acc = glb.json.accessors[index];
  const view = glb.json.bufferViews[acc.bufferView];
  const T = CTYPES[acc.componentType];
  const n = COMPONENTS[acc.type];
  const elemBytes = T.BYTES_PER_ELEMENT * n;
  const stride = view.byteStride || elemBytes;
  const base = glb.bin.byteOffset + (view.byteOffset || 0) + (acc.byteOffset || 0);
  if (stride === elemBytes && base % T.BYTES_PER_ELEMENT === 0) return new T(glb.bin.buffer, base, acc.count * n).slice();
  const out = new T(acc.count * n);
  const src = new DataView(glb.bin.buffer);
  const get = {
    5120: (o) => src.getInt8(o),
    5121: (o) => src.getUint8(o),
    5122: (o) => src.getInt16(o, true),
    5123: (o) => src.getUint16(o, true),
    5125: (o) => src.getUint32(o, true),
    5126: (o) => src.getFloat32(o, true),
  }[acc.componentType];
  for (let i = 0; i < acc.count; i++) for (let k = 0; k < n; k++) out[i * n + k] = get(base + i * stride + k * T.BYTES_PER_ELEMENT);
  return out;
}

/** Non-indexed world-space triangle positions of a mesh (the generator writes no node transforms). */
export function meshTrianglePositions(glb, meshIndex) {
  const mesh = glb.json.meshes[meshIndex];
  const parts = [];
  let total = 0;
  for (const prim of mesh.primitives) {
    const pos = readAccessor(glb, prim.attributes.POSITION);
    const idx = prim.indices !== undefined ? readAccessor(glb, prim.indices) : null;
    const count = idx ? idx.length : pos.length / 3;
    const out = new Float32Array(count * 3);
    for (let i = 0; i < count; i++) {
      const v = idx ? idx[i] : i;
      out[i * 3] = pos[v * 3];
      out[i * 3 + 1] = pos[v * 3 + 1];
      out[i * 3 + 2] = pos[v * 3 + 2];
    }
    parts.push(out);
    total += out.length;
  }
  if (parts.length === 1) return parts[0];
  const all = new Float32Array(total);
  let o = 0;
  for (const p of parts) {
    all.set(p, o);
    o += p.length;
  }
  return all;
}

function geometryOf(positions) {
  const g = new BufferGeometry();
  g.setAttribute('position', new Float32BufferAttribute(positions, 3));
  return g;
}

// collision class -> BVH group of src/physics/collisionWorld.js (flags: which rays the group stops)
export const COLLISION_GROUPS = {
  main: { group: 'main', bullets: true, vision: true },
  move: { group: 'move', bullets: false, vision: false },
  movevis: { group: 'movevis', bullets: false, vision: true },
};

/** Level solids from the collision GLB (one solid per collision set). */
export function collisionSolidsFromGlb(glb) {
  const out = [];
  for (const node of glb.json.nodes || []) {
    const iv = node.extras && node.extras.iv;
    if (!iv || node.mesh === undefined || !iv.class) continue;
    const grp = COLLISION_GROUPS[iv.class] || COLLISION_GROUPS.main;
    const id = `geo:${iv.class}:${iv.surface}${iv.nav === false ? ':nonav' : ''}`;
    const solid = { id, parent: id, mat: iv.surface || 'concrete', collide: true, geometry: geometryOf(meshTrianglePositions(glb, node.mesh)), nav: iv.nav !== false };
    if (grp.group !== 'main') solid.bvhGroup = grp.group;
    out.push(solid);
  }
  return out;
}

/** Terrain collision solids (all terrain tiles merged into one solid, surface resolved by the raster). */
export function terrainSolidsFromGlb(glb) {
  const parts = [];
  let total = 0;
  for (const node of glb.json.nodes || []) {
    const iv = node.extras && node.extras.iv;
    if (!iv || iv.collision !== 'terrain' || node.mesh === undefined) continue;
    const p = meshTrianglePositions(glb, node.mesh);
    parts.push(p);
    total += p.length;
  }
  if (!parts.length) return [];
  const all = new Float32Array(total);
  let o = 0;
  for (const p of parts) {
    all.set(p, o);
    o += p.length;
  }
  return [{ id: 'geo:terrain', parent: 'geo:terrain', mat: 'terrain', collide: true, geometry: geometryOf(all), nav: true, terrain: true }];
}

/**
 * Surface raster of the terrain: surfaceAt(x, z) in three.js coordinates -> surface name (grass, asphalt, gravel,
 * dirt, mud, forest_floor, concrete, paving, water, stone, ...), null outside the raster.
 */
export function surfaceRasterFromGlb(glb) {
  const iv = glb.json.asset && glb.json.asset.extras && glb.json.asset.extras.iv;
  const sr = iv && iv.surfaceRaster;
  if (!sr) return null;
  const data = readAccessor(glb, sr.accessor);
  const { width, height, x0, y0, res, surfaces } = sr;
  const yTop = y0 + height * res; // level y of the north edge (row 0)
  return {
    width,
    height,
    res,
    surfaces,
    data,
    surfaceAt(x, z) {
      const ly = -z; // level y
      const i = Math.floor((x - x0) / res);
      const j = Math.floor((yTop - ly) / res);
      if (i < 0 || j < 0 || i >= width || j >= height) return null;
      return surfaces[data[j * width + i]] || null;
    },
  };
}

/** Terrain / albedo rectangle of the terrain GLB (level frame x0, y0, x1, y1). */
export function albedoRectFromGlb(glb) {
  const iv = glb.json.asset && glb.json.asset.extras && glb.json.asset.extras.iv;
  return iv && iv.albedoRect ? iv.albedoRect : null;
}

/**
 * All geometry solids of a level with a `geometry` block, plus its surface raster.
 * @param {object} level level JSON
 * @param {(path:string)=>Promise<ArrayBuffer>|ArrayBuffer} fetchBytes reads an asset path (relative to public/)
 */
export async function loadGeometryCollision(level, fetchBytes) {
  const g = level.geometry;
  if (!g) return { solids: [], surfaceRaster: null, terrainGlb: null };
  const [colBuf, terBuf] = await Promise.all([fetchBytes(g.collision), fetchBytes(g.terrain)]);
  const colGlb = parseGlb(colBuf);
  const terGlb = parseGlb(terBuf);
  const solids = [...terrainSolidsFromGlb(terGlb), ...collisionSolidsFromGlb(colGlb)];
  return { solids, surfaceRaster: surfaceRasterFromGlb(terGlb), terrainGlb: terGlb, collisionGlb: colGlb };
}
