import { createArenaSession, run, idleCmd, DT } from './aiSim.mjs';
const ctx = createArenaSession({ bots: [5, 6, 6], withPlayer: true, seed: 61, zone: 'arena_center' });
const upd = ctx.ai.update;
const cpu = []; const wall = [];
ctx.session.ai.update = (dt) => { const c0 = process.cpuUsage(); const w0 = performance.now(); upd(dt); const c1 = process.cpuUsage(c0); cpu.push((c1.user + c1.system) / 1000); wall.push(performance.now() - w0); };
const s0 = process.cpuUsage(); const t0 = performance.now();
run(ctx, Math.round(120 / DT), { playerCmd: idleCmd() });
const tot = process.cpuUsage(s0); const tw = performance.now() - t0;
const q = (a, p) => { const s = a.slice().sort((x, y) => x - y); return s[Math.floor(s.length * p)]; };
const mean = (a) => a.reduce((x, y) => x + y, 0) / a.length;
console.log(JSON.stringify({ ticks: cpu.length, aiCpuMsMean: +mean(cpu).toFixed(3), aiCpuMsP50: +q(cpu, 0.5).toFixed(3), aiCpuMsP99: +q(cpu, 0.99).toFixed(3), aiWallMsMean: +mean(wall).toFixed(3), wholeSimCpuMsPerTick: +((tot.user + tot.system) / 1000 / cpu.length).toFixed(3), wallS: +(tw / 1000).toFixed(1) }));
