// Kalné Hamry (generated by Tools/level/export_web_level.py from Shared/level/layout.json + buildings.json):
// level data, freshness of the generated files, collision classes (sight / bullets / capsule), surfaces, spawns,
// armory crates, zones, boundary, the baked navmesh (spawn -> zone for every team and zone) and a short 17-bot
// match on the real game integration in Node.
import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Vector3 } from 'three';
import { loadLevelData } from '../../src/game/levels.js';
import { levelWorld, runMatch } from '../../tools/match_report.mjs';
import { NavService } from '../../src/ai/nav/navService.js';
import { pointInZone, pointInPolygonXZ } from '../../src/game/zoneShape.js';
import { BoundarySystem } from '../../src/game/boundary.js';
import attachments from '../../src/data/attachments.json' with { type: 'json' };

const here = path.dirname(fileURLToPath(import.meta.url));
const WEB = path.resolve(here, '..', '..');
const REPO = path.resolve(WEB, '..');
const sha = (p, n) => createHash('sha256').update(readFileSync(p)).digest('hex').slice(0, n);

const level = await loadLevelData('kalne_hamry');
const world = levelWorld(level);
const nav = new NavService(JSON.parse(readFileSync(path.join(WEB, 'public', level.nav.file), 'utf8')));

test('level data: name, tag, three polygon zones, 3 x 16 spawn candidates with rows per zone, armories, boundary, cover, QA points', () => {
  assert.equal(level.displayName, 'Kalné Hamry');
  assert.equal(level.tag, 'pracovní verze (provizorní grafika)');
  const m = level.match;
  assert.deepEqual(m.zones.map((z) => z.id), ['zone_dilna', 'zone_sklad', 'zone_dvur']);
  for (const z of m.zones) {
    assert.ok(z.polygon.length >= 4 && z.yMax > z.yMin && z.radius > 5, z.id);
  }
  assert.equal(m.teamSpawns.length, 3);
  for (const list of m.teamSpawns) {
    assert.equal(list.length, 16);
    for (const zid of ['zone_dilna', 'zone_sklad', 'zone_dvur']) assert.equal(list.filter((s) => s.zones.includes(zid)).length, 8, `8 active points per zone (${zid})`);
  }
  assert.equal(m.armories.length, 6, 'one crate per spawn row');
  assert.deepEqual([0, 1, 2].map((t) => m.armories.filter((a) => a.team === t).length), [2, 2, 2]);
  assert.ok(level.boundary.soft.length > 10 && level.boundary.hard.length > 10 && level.boundary.countdownS === 10);
  assert.match(level.boundary.text.leaving, /\{s\}/);
  assert.ok(level.cover.length >= 800, 'design cover points');
  assert.ok(level.cover.some((c) => c.kind === 'window') && level.cover.some((c) => c.kind === 'stair_watch') && level.cover.some((c) => c.kind === 'interior_object'));
  assert.ok(level.qaPoints.length >= 170);
});

test('generated files are fresh: source data and GLB hashes match what the level JSON was generated from', () => {
  assert.equal(level.sources['Shared/level/layout.json'], sha(path.join(REPO, 'Shared/level/layout.json'), 64), 'layout.json changed: run python3 Tools/level/export_web_level.py');
  assert.equal(level.sources['Shared/level/buildings.json'], sha(path.join(REPO, 'Shared/level/buildings.json'), 64), 'buildings.json changed: run python3 Tools/level/export_web_level.py');
  for (const [f, h] of Object.entries(level.geometry.files)) {
    const p = path.join(WEB, 'public', 'assets', 'levels', 'kalne_hamry', f);
    assert.ok(existsSync(p), p);
    assert.equal(sha(p, 16), h, `${f} does not match the level JSON`);
    // the Artifact host limit: 15 MiB per file after base64
    assert.ok((readFileSync(p).length * 4) / 3 < 15 * 1048576, `${f} over 15 MiB as base64`);
  }
});

test('collision classes: glass and chain-link stop only capsules, hedges stop capsules and sight, walls stop everything', () => {
  const groups = Object.fromEntries(world.parts.map((p) => [p.name, p]));
  assert.ok(groups.main && groups.move && groups.movevis, world.parts.map((p) => p.name).join(','));
  assert.deepEqual([groups.move.flags.bullets, groups.move.flags.vision], [false, false]);
  assert.deepEqual([groups.movevis.flags.bullets, groups.movevis.flags.vision], [false, true]);
  // probe the middle of a triangle of each class from 0.4 m in front of it
  const probe = (part, solidPrefix) => {
    const pos = part.geometry.getAttribute('position');
    for (let t = 0; t < part.triangleCount; t++) {
      const sid = part.solids[part.solidOfVertex[t * 3]].id;
      if (!sid.startsWith(solidPrefix)) continue;
      const a = new Vector3().fromBufferAttribute(pos, t * 3);
      const b = new Vector3().fromBufferAttribute(pos, t * 3 + 1);
      const c = new Vector3().fromBufferAttribute(pos, t * 3 + 2);
      const n = new Vector3().subVectors(b, a).cross(new Vector3().subVectors(c, a));
      if (n.length() < 0.05 || Math.abs(n.normalize().y) > 0.2) continue; // a large vertical face
      const m = a.clone().add(b).add(c).divideScalar(3);
      const o = m.clone().addScaledVector(n, 0.4);
      const d = n.clone().negate();
      const any = world.raycast(o, d, 0.5);
      if (!any || any.solidId !== sid) continue; // occluded by something else: try another triangle
      return { any, bullets: world.raycast(o, d, 0.5, 0, 'bullets'), vision: world.raycast(o, d, 0.5, 0, 'vision') };
    }
    return null;
  };
  const glass = probe(groups.move, 'geo:move:glass');
  assert.ok(glass, 'a window pane');
  assert.equal(glass.bullets, null, 'bullets pass the glass');
  assert.equal(glass.vision, null, 'sight passes the glass');
  const fence = probe(groups.move, 'geo:move:metal');
  assert.ok(fence && fence.bullets === null && fence.vision === null, 'chain-link / rails: bullets and sight pass');
  const hedge = probe(groups.movevis, 'geo:movevis:grass');
  assert.ok(hedge, 'a hedge / shrub');
  assert.equal(hedge.bullets, null, 'bullets pass the hedge');
  assert.ok(hedge.vision && hedge.vision.solidId === 'geo:movevis:grass', 'sight is blocked by the hedge');
  const wall = probe(groups.main, 'geo:main:concrete');
  assert.ok(wall && wall.bullets && wall.vision, 'walls stop bullets and sight');
});

test('terrain surfaces for footsteps and impacts come from the design surface regions', () => {
  const r = world.surfaceRaster;
  const at = (x, y) => r.surfaceAt(x, -y); // level (x, y) -> three (x, -y)
  const L = JSON.parse(readFileSync(path.join(REPO, 'Shared/level/layout.json'), 'utf8'));
  const road = L.roads.find((x) => x.id === 'ROAD_B').polyline;
  assert.equal(at((road[2][0] + road[3][0]) / 2, (road[2][1] + road[3][1]) / 2), 'asphalt');
  const brook = L.water[0].polyline;
  assert.equal(at(brook[6][0], brook[6][1]), 'water');
  assert.equal(at(-2, -8), 'paving', 'the village square (granite setts)');
  const spawnB = L.spawn_areas.find((s) => s.team === 'bravo').candidate_points[0].pos;
  assert.equal(at(spawnB[0], spawnB[1]), 'gravel', 'the gravel works spawn');
});

test('spawn candidates stand on free ground; the armory crate of every row is within reach and clear of the points', () => {
  const down = new Vector3(0, -1, 0);
  for (const [t, list] of level.match.teamSpawns.entries()) {
    for (const s of list) {
      const p = new Vector3().fromArray(s.pos);
      const g = world.raycast(p.clone().setY(p.y + 1.5), down, 3);
      assert.ok(g && Math.abs(g.point.y - p.y) < 0.12, `${s.id}: ground under the point (${g && g.point.y})`);
      for (let k = 0; k < 8; k++) {
        const a = (k / 8) * Math.PI * 2;
        for (const h of [0.5, 1.0, 1.6]) {
          const hit = world.raycast(p.clone().setY(p.y + h), new Vector3(Math.cos(a), 0, Math.sin(a)), 0.4);
          assert.equal(hit, null, `${s.id}: capsule room at ${h} m (${hit && hit.solidId})`);
        }
      }
      assert.equal(new BoundarySystem(level.boundary).classify(p), 'inside', `${s.id} not in the boundary warning band`);
      assert.ok(nav.mesh.closestPoint(p, { maxDist: 0.8, group: nav.mainGroup }), `${s.id} on the main navmesh`);
    }
    for (const a of level.match.armories.filter((x) => x.team === t)) {
      const row = list.filter((s) => s.row === a.row);
      const dmin = Math.min(...row.map((s) => Math.hypot(s.pos[0] - a.center[0], s.pos[2] - a.center[2])));
      assert.ok(dmin <= attachments.armory.interactRadiusM + 2.5, `${a.id}: ${dmin.toFixed(2)} m from its row`);
      assert.ok(dmin >= 1.2, `${a.id} clear of the spawn points (${dmin.toFixed(2)} m)`);
    }
  }
});

test('zones: polygon + height band (the first floor of the house above the garden zone does not count)', () => {
  const m = Object.fromEntries(level.qaPoints.map((q) => [q.id, q]));
  const zones = Object.fromEntries(level.match.zones.map((z) => [z.id, z]));
  for (const id of ['zone_dilna', 'zone_sklad', 'zone_dvur']) {
    const q = m[`QA_${id}_center`];
    assert.ok(pointInZone({ x: q.pos[0], y: q.pos[1], z: q.pos[2] }, zones[id]), `${id} centre counts`);
  }
  const up = m.QA_zone_dvur_above_DM_R1_LOZ_Z;
  assert.ok(pointInPolygonXZ(zones.zone_dvur.polygon, up.pos[0], up.pos[2]), 'inside the polygon');
  assert.equal(pointInZone({ x: up.pos[0], y: up.pos[1], z: up.pos[2] }, zones.zone_dvur), false, 'above the height band');
});

test('boundary: warning band, countdown outside the soft line, death "Minové pole" after 10 s', () => {
  const b = new BoundarySystem(level.boundary);
  const hard = level.boundary.hard[0];
  const outside = { x: hard[0], y: 0, z: hard[1] };
  const c = { id: 'x', alive: true, position: outside };
  let died = 0;
  for (let i = 0; i < 9.9 * 60; i++) b.update(1 / 60, [c], () => died++);
  assert.equal(died, 0);
  const info = b.info('x');
  assert.equal(info.status, 'outside');
  assert.match(info.text, /Opouštíš bojový prostor! Vrať se: 1 s/);
  for (let i = 0; i < 12; i++) b.update(1 / 60, [c], () => died++);
  assert.equal(died, 1, 'dies after 10 s outside');
  const soft = level.boundary.soft[0];
  const warn = level.boundary.warning[0];
  const between = { x: (soft[0] * 0.8 + warn[0] * 1.2) / 2, y: 0, z: (soft[1] * 0.8 + warn[1] * 1.2) / 2 };
  assert.equal(b.classify(between), 'warning');
});

test('navmesh: every team reaches every zone from its active spawn row; doors and stairs are on the main navmesh', () => {
  const qa = Object.fromEntries(level.qaPoints.map((q) => [q.id, q]));
  for (const z of level.match.zones) {
    const goal = new Vector3().fromArray(qa[`QA_${z.id}_center`].pos);
    level.match.teamSpawns.forEach((list, t) => {
      const sp = list.find((s) => s.zones.includes(z.id));
      const r = nav.findPath(new Vector3().fromArray(sp.pos), goal);
      assert.ok(r.ok && !r.partial, `team ${t} -> ${z.id}: ${r.reason}`);
      assert.ok(r.length > 60 && r.length < 220, `team ${t} -> ${z.id}: ${r.length.toFixed(1)} m`);
    });
  }
  const off = level.qaPoints
    .filter((q) => q.kind === 'doorway' || q.kind === 'stair')
    .filter((q) => {
      const cl = nav.mesh.closestPoint(new Vector3().fromArray(q.pos), { maxDist: 1.0 });
      return !cl || nav.mesh.nodes[cl.node].group !== nav.mainGroup;
    })
    .map((q) => q.id);
  assert.deepEqual(off, [], 'doors / stairs off the main navmesh');
  const baked = JSON.parse(readFileSync(path.join(WEB, 'public', level.nav.file), 'utf8'));
  for (const [zid, r] of Object.entries(baked.reachability)) for (const [team, v] of Object.entries(r.teams)) assert.equal(v.unreachable, 0, `${team} -> ${zid}`);
  assert.ok(baked.cover.filter((c) => c.kind === 'window').length >= 10 && baked.cover.some((c) => c.kind === 'stair_watch'), 'design window / stair-watch cover in the bake');
});

test('17 bots on Kalné Hamry (Node, real integration): 60 s without errors, teleports or long stuck episodes; bots reach the zone', () => {
  const r = runMatch({ level: 'kalne_hamry', bots: [5, 6, 6], seconds: 60, seed: 4, zone: 'zone_sklad' });
  assert.deepEqual(r.consoleErrors, []);
  assert.equal(r.jumps.teleports, 0);
  assert.ok(r.stuck.maxS < 5, `stuck ${r.stuck.maxS} s`);
  assert.ok(r.kills.reduce((u, v) => u + v, 0) > 0, 'combat happened');
  assert.ok(r.zone.presenceS.some((s) => s > 0), `somebody reached the zone in 60 s (${r.zone.presenceS})`);
});
